api/urls.py
# from django.urls import path, include
# from .views import ProductoList, ProductoDetalle, \
#     ClienteList

# urlpatterns = [
#     path('v1/productos/',ProductoList.as_view(),name='producto_list'),
#     path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
#     path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
# ]

fichas/urls.py
from django.urls import path
from .views import inscripcion, lista_inscritos, ubigeo_form, editar_proceso, eliminar_proceso

app_name = "inv"

urlpatterns = [
    path("inscripcion", inscripcion , name = "inscripcion"),
    path("lista_inscritos", lista_inscritos , name= "lista_inscritos"),
    path("editar_proceso/<int:proceso_id>/", editar_proceso, name="editar_proceso"),
    path("eliminar_proceso/<int:proceso_id>/", eliminar_proceso, name="eliminar_proceso"),
    path('form/', ubigeo_form, name='ubigeo_form'),
]

proyecto/urls.py
from fichas import views
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('inscripcion/', views.inscripcion, name='inscripcion'),
    #path('get_person_data/', views.get_person_data, name='get_person_data'),
    path('',include(('bases.urls','bases'), namespace='bases')),
    path('fichas/',include(('fichas.urls','fichas'), namespace='fichas')),
    #path('select2/', include('django_select2.urls')),
    path('admin/', admin.site.urls),
]

fichas/models.py
from django.db import models


class DniProcesos(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    id_operario = models.CharField(db_column='IdOperario', max_length=60, blank=True, null=True)  # Field name made lowercase.
    id_seccion = models.CharField(db_column='IdSeccion', max_length=30, blank=True, null=True)  # Field name made lowercase.
    nombre = models.CharField(max_length=100, blank=True, null=True)





class Procesos(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)  # Field name made lowercase.
    id_ordenproduccion = models.CharField(db_column='IdOrdenProduccion', max_length=100)  # Field name made lowercase.
    id_operario = models.CharField(db_column='IdOperario', max_length=100)  # Field name made lowercase.
    id_seccion = models.CharField(db_column='IdSeccion', max_length=100)  # Field name made lowercase.
    fecha_hora = models.CharField(db_column='FechaHora', max_length=50, blank=True, null=True)  # Field name made lowercase.
    tipo = models.CharField(db_column='Tipo', max_length=15, blank=True, null=True)  # Field name made lowercase.
    modelo = models.CharField(db_column='Modelo', max_length=50, blank=True, null=True)  # Field name made lowercase.
    categoria = models.CharField(db_column='Categoria', max_length=50, blank=True, null=True)  # Field name made lowercase.
    tarifa = models.DecimalField(db_column='Tarifa', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.




class Seccionesexcel(models.Model):
    seccion = models.CharField(max_length=255, blank=True, null=True)
    libro = models.CharField(max_length=255, blank=True, null=True)
    recepcion_fecha = models.CharField(max_length=255, blank=True, null=True)
    asignacion_fecha = models.CharField(max_length=255, blank=True, null=True)
    asignacion_persona = models.CharField(max_length=255, blank=True, null=True)
    final_fecha = models.CharField(max_length=255, blank=True, null=True)

fichas/forms.py
from django import forms
from django_select2.forms import ModelSelect2Widget
from .models import Procesos 

class ProcesosForm(forms.ModelForm):
    class Meta:
        model = Procesos
        fields = '__all__'
        widgets = {
            'id_ordenproduccion' : forms.TextInput(),
            'id_operario' : forms.TextInput(),
            'id_seccion' : forms.TextInput(),
            'fecha_hora': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'tipo' : forms.TextInput(),
            'modelo' : forms.TextInput(),
            'categoria' : forms.TextInput(),
            'tarifa': forms.NumberInput(attrs={'step': '0.01'}),
        }  


# class FichaInscripcionForm(forms.ModelForm):
#     referido_por = forms.ModelChoiceField(
#         queryset=FichaInscripcion.objects.all(),
#         required=False,
#         widget=forms.Select(attrs={'class': 'form-control'})
#     )

#     class Meta:
#         model = FichaInscripcion
#         fields = [
#             'dni', 'nombres', 'apellido_paterno', 'apellido_materno', 'fecha_nacimiento', 'referido_por',
#             'lugar_nacimiento', 'telefono_fijo', 'celular', 'email', 'sexo', 'estado_civil',
#             'grado_instruccion', 'profesion', 'direccion', 'distrito', 'provincia', 
#             'departamento', 'centro_laboral', 'cargo_laboral', 'direccion_laboral',
#             'distrito_laboral', 'provincia_laboral', 'departamento_laboral',
#         ]
#         widgets = {
#             'fecha_nacimiento': forms.DateInput(attrs={'type': 'date'}),
#             'dni': forms.TextInput(attrs={'id': 'dni', 'maxlength': '8'}),
#             'sexo': forms.RadioSelect(),
#             'estado_civil': forms.Select(),
#             'grado_instruccion': forms.Select(),
#             'email': forms.EmailInput(attrs={'type': 'email'}),
#             'celular': forms.TextInput(attrs={'type': 'tel'}),
#             'telefono_fijo': forms.TextInput(attrs={'type': 'tel'}),
#             'direccion': forms.Textarea(attrs={
#                 'class': 'form-control',
#                 'maxlength': '100',
#                 'style': 'width: 100%; height: 100px;'  # Ajusta el ancho al 100% del contenedor
#             }),
#             'direccion_laboral': forms.Textarea(attrs={
#                 'class': 'form-control',
#                 'maxlength': '100',
#                 'style': 'width: 100%; height: 100px;'  # Ajusta el ancho al 100% del contenedor
#             }),
#         }

#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.fields:
#             if not isinstance(self.fields[field].widget, (forms.RadioSelect, forms.CheckboxSelectMultiple)):
#                 self.fields[field].widget.attrs.update({'class': 'form-control'})

#     def clean_dni(self):
#         dni = self.cleaned_data.get('dni')
#         if not dni.isdigit() or len(dni) != 8:
#             raise forms.ValidationError("El DNI debe ser un número de 8 dígitos.")
#         return dni

#     def clean_email(self):
#         email = self.cleaned_data.get('email')
#         if FichaInscripcion.objects.filter(email=email).exists():
#             raise forms.ValidationError("Este email ya está registrado.")
#         return email

#     def clean_celular(self):
#         celular = self.cleaned_data.get('celular')
#         if not celular.isdigit() or len(celular) != 9:
#             raise forms.ValidationError("El número de celular debe tener 9 dígitos.")
#         return celular

fichas/views.py
from django.shortcuts import render, redirect , get_object_or_404
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.decorators import login_required, permission_required
from django.views.decorators.http import require_GET
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.contrib import messages
from .forms import ProcesosForm
from .apis_net_pe import ApisNetPe
from .models import Procesos
# from .models import Ubigeo
def editar_proceso(request, proceso_id):
    proceso = get_object_or_404(Procesos, id=proceso_id)
    if request.method == 'POST':
        form = ProcesosForm(request.POST, instance=proceso)
        if form.is_valid():
            form.save()
            messages.success(request, 'Proceso actualizado correctamente.')
            return redirect('inv:lista_inscritos')
    else:
        form = ProcesosForm(instance=proceso)
    
    return render(request, 'inv/inscripcion.html', {'form': form})

def eliminar_proceso(request, proceso_id):
    proceso = get_object_or_404(Procesos, id=proceso_id)
    if request.method == 'POST':
        proceso.delete()
        messages.success(request, 'Proceso eliminado correctamente.')
        return redirect('inv:lista_inscritos')
    
    return render(request, 'inv/eliminar_confirmacion.html', {'proceso': proceso})

def ubigeo_form(request):
    return render(request, 'inv/form.html')
# def search_ubigeo(request):
#     if 'term' in request.GET:
#         qs = Ubigeo.objects.filter(ubigeo__icontains=request.GET.get('term'))
#         ubigeos = list(qs.values('codubigeo', 'ubigeo', 'coddep', 'departamento', 'codprov', 'provincia'))
#         return JsonResponse(ubigeos, safe=False)
#     return JsonResponse([], safe=False)


def inscripcion(request):
    if request.method == 'POST':
        form = ProcesosForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Proceso ingresado correctamente.')
            return redirect('inv:lista_inscritos')
    else:
        form = ProcesosForm()
    
    return render(request, 'inv/inscripcion.html', {'form': form})

# def inscripcion(request):
#     if request.method == 'POST':
#         form = ProcesosForm(request.POST)
#         if form.is_valid():
#             ficha = form.save()
#             messages.success(request, f'Inscripción exitosa para {ficha.modelo} {ficha.categoria}')
#             return redirect('inv:lista_inscritos')
#         else:
#             messages.error(request, 'Por favor, corrige los errores en el formulario.')
#     else:
#         form = ProcesosForm()
#     return render(request, 'inv/inscripcion.html', {'form': form})

# def get_person_data(request):
#     dni = request.GET.get('dni', None)
#     if dni:
#         print(f"Buscando DNI: {dni}")  # Agrega este print para ver si el DNI se está recibiendo correctamente
#         try:
#             ficha = ProcesosForm.objects.get(dni=dni)
#             data = {
#                 'fecha_hora': ficha.fecha_hora,
#                 'tipo' : ficha.tipo,
#                 'modelo' : ficha.modelo,
#                 'categoria' : ficha.categoria,
#                 'tarifa' : ficha.tarifa,
#             }
#             return JsonResponse(data)
#         except ProcesosForm.DoesNotExist:
#             print("DNI no encontrado.")  # Agrega este print para depurar
#             return JsonResponse({'error': 'No se encontró ninguna persona con ese DNI.'}, status=404)
#     print("DNI no proporcionado.")  # Agrega este print para depurar
#     return JsonResponse({'error': 'DNI no proporcionado.'}, status=400)


def lista_inscritos(request):
    inscritos = Procesos.objects.all().order_by('-fecha_hora')  # Asegúrate de que el nombre del campo es 'fechahora'
    return render(request, 'inv/lista_inscritos.html', {'inscritos': inscritos})

class BaseView(LoginRequiredMixin, PermissionRequiredMixin):
    login_url = 'bases:login'
    
    def handle_no_permission(self):
        messages.error(self.request , "No tienes permiso para acceder a esta página.")
        return redirect('config:home')

fichas/templates/inv/eliminar_confirmacion.html
{% extends 'base/index.html' %}

{% block content %}
<div class="container mt-5">
    <h2>¿Estás seguro de que deseas eliminar este proceso?</h2>
    <p><strong>Tipo:</strong> {{ proceso.tipo }}</p>
    <p><strong>Modelo:</strong> {{ proceso.modelo }}</p>
    <p><strong>Categoría:</strong> {{ proceso.categoria }}</p>
    <p><strong>Tarifa:</strong> {{ proceso.tarifa }}</p>
    <p><strong>Fecha y Hora:</strong> {{ proceso.fecha_hora }}</p>
    
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'inv:lista_inscritos' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

fichas/templates/inv/form.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autocompletado de Ubigeos</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <style>
        .ui-autocomplete {
            max-height: 200px;
            overflow-y: auto;
            overflow-x: hidden;
            z-index: 1000;
        }
        .ui-menu-item {
            padding: 5px 10px;
            font-size: 14px;
        }
        .ui-menu-item-wrapper.ui-state-active {
            background-color: #007bff;
            color: white;
        }
    </style>
</head>
<body>
    <div class="container mt-5">
        <h1>Buscar Distrito</h1>
        <div class="form-group">
            <label for="ubigeo-search">Buscar Distrito:</label>
            <input type="text" id="ubigeo-search" class="form-control">
        </div>
        <div class="form-group">
            <label for="codubigeo">Código Ubigeo:</label>
            <input type="text" id="codubigeo" class="form-control" readonly>
        </div>
        <div class="form-group">
            <label for="departamento">Departamento:</label>
            <input type="text" id="departamento" class="form-control" readonly>
        </div>
        <div class="form-group">
            <label for="provincia">Provincia:</label>
            <input type="text" id="provincia" class="form-control" readonly>
        </div>
    </div>

    <script>
    $(function() {
        $("#ubigeo-search").autocomplete({
            source: "{% url 'fichas:search_ubigeo' %}",
            minLength: 2,
            select: function(event, ui) {
                $('#codubigeo').val(ui.item.codubigeo);
                $('#departamento').val(ui.item.departamento);
                $('#provincia').val(ui.item.provincia);
            }
        }).autocomplete("instance")._renderItem = function(ul, item) {
            return $("<li>")
                .append("<div><strong>" + item.ubigeo + "</strong><br><small>" + item.provincia + ", " + item.departamento + "</small></div>")
                .appendTo(ul);
        };
    });
    </script>
</body>
</html>

fichas/templates/inv/inscripcion.html
{% extends 'base/index.html' %}

{% block content %}
<div class="container mt-5">
    <div class="card">
        <div class="card-header">
            Datos Proceso
        </div>
        <div class="card-body">
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="personal" role="tabpanel" aria-labelledby="personal-tab">
                    <form id="procesosForm" method="post">
                        {% csrf_token %}
                        <div class="row mt-3">
                            <div class="col-md-6">
                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.id_ordenproduccion.id_for_label }}" class="col-form-label col-md-3">Id Orden Producción:</label>
                                    <div class="col-md-9">
                                        {{ form.id_ordenproduccion }}
                                    </div>
                                </div>
                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.id_operario.id_for_label }}" class="col-form-label col-md-3">Id Operario:</label>
                                    <div class="col-md-9">
                                        {{ form.id_operario }}
                                    </div>
                                </div>
                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.id_seccion.id_for_label }}" class="col-form-label col-md-3">Id Sección:</label>
                                    <div class="col-md-9">
                                        {{ form.id_seccion }}
                                    </div>
                                </div>
                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.tipo.id_for_label }}" class="col-form-label col-md-3">Tipo:</label>
                                    <div class="col-md-9">
                                        {{ form.tipo }}
                                    </div>
                                </div>
                                
                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.modelo.id_for_label }}" class="col-form-label col-md-3">Modelo:</label>
                                    <div class="col-md-9">
                                        {{ form.modelo }}
                                    </div>
                                </div>

                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.categoria.id_for_label }}" class="col-form-label col-md-3">Categoría:</label>
                                    <div class="col-md-9">
                                        {{ form.categoria }}
                                    </div>
                                </div>

                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.tarifa.id_for_label }}" class="col-form-label col-md-3">Tarifa:</label>
                                    <div class="col-md-9">
                                        {{ form.tarifa }}
                                    </div>
                                </div>

                                <div class="form-group d-flex align-items-center">
                                    <label for="{{ form.fecha_hora.id_for_label }}" class="col-form-label col-md-3">Fecha Hora:</label>
                                    <div class="col-md-9">
                                        {{ form.fecha_hora }}
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="text-right mt-3">
                            <button type="submit" class="btn btn-success btn-custom">Guardar</button>
                            <button type="button" class="btn btn-danger btn-custom" id="cancelarBtn">Cancelar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
document.getElementById('procesosForm').addEventListener('submit', function(event) {
    event.preventDefault(); // Evita el envío tradicional del formulario
    
    const form = this;
    const formData = new FormData(form);
    
    fetch(form.action, {
        method: form.method,
        body: formData,
        headers: {
            'X-CSRFToken': formData.get('csrfmiddlewaretoken')
        }
    }).then(response => {
        if (response.ok) {
            Swal.fire({
                title: 'Éxito',
                text: 'Proceso ingresado correctamente.',
                icon: 'success',
                confirmButtonText: 'Aceptar'
            }).then(() => {
                window.location.href = "{% url 'inv:lista_inscritos' %}"; // Redirigir después de aceptar el mensaje
            });
        } else {
            Swal.fire({
                title: 'Error',
                text: 'Hubo un problema al guardar el proceso.',
                icon: 'error',
                confirmButtonText: 'Aceptar'
            });
        }
    }).catch(error => {
        Swal.fire({
            title: 'Error',
            text: 'Hubo un problema al procesar la solicitud.',
            icon: 'error',
            confirmButtonText: 'Aceptar'
        });
    });
});

document.getElementById('cancelarBtn').addEventListener('click', function(event) {
    event.preventDefault();
    Swal.fire({
        title: '¿Estás seguro?',
        text: "¡No podrás revertir esto!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Sí, estoy seguro'
    }).then((result) => {
        if (result.isConfirmed) {
            window.location.href = "{% url 'fichas:lista_inscritos' %}";
        }
    });
});
</script>
{% endblock %}

fichas/templates/inv/inscripcion_exitosa.html
{% comment %} {% extends 'base/index.html' %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">Inscripción Exitosa</h1>
    <p>¡Felicidades! Tu inscripción ha sido completada con éxito.</p>
    <a href="{% url 'inscripcion' %}" class="btn btn-primary">Nueva Inscripción</a>
    <a href="{% url 'lista_inscritos' %}" class="btn btn-secondary">Ver Lista de Inscritos</a>
    <a href="{% url 'inscripcion' %}" class="btn btn-primary">Volver al Formulario</a>
</div>
{% endblock %} {% endcomment %}

fichas/templates/inv/lista_inscritos.html
{% extends 'base/index.html' %}

{% block content %}
<div class="container mt-5">
    <h1>Lista de Procesos</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Tipo</th>
                <th>Modelo</th>
                <th>Categoría</th>
                <th>Tarifa</th>
                <th>Fecha y Hora</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for inscrito in inscritos %}
            <tr>
                <td>{{ inscrito.tipo }}</td>
                <td>{{ inscrito.modelo }}</td>
                <td>{{ inscrito.categoria }}</td>
                <td>{{ inscrito.tarifa }}</td>
                <td>{{ inscrito.fecha_hora }}</td>
                <td>
                    <a href="{% url 'inv:editar_proceso' inscrito.id %}" class="btn btn-sm btn-success">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                    <a href="{% url 'inv:eliminar_proceso' inscrito.id %}" class="btn btn-sm btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar este proceso?');">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <a href="{% url 'inv:inscripcion' %}" class="btn btn-primary">Nuevo Proceso</a>
</div>
{% endblock %}